name: Create Release on Push to Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    container: ghcr.io/lukaspanni/pandoc-builder:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build PDFs
        shell: pwsh
        run: ./build.ps1
      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pdf-output
          path: build.zip

  create_release:
    needs: build_pdf
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download PDF artifacts
        uses: actions/download-artifact@v4
        with:
          name: pdf-output
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ls -R
          gh release create $(date +'%Y-%m-%d-%H-%M') build.zip --generate-notes
